// Array of Bitcoin slogans

// These were removed because it seems they're confusing for kids, at least without context:
// en: "'The Times 03/Jan/2009 Chancellor on brink of second bailout for banks' -- Satoshi Nakamoto",
// en: "'I am not Dorian Nakamoto.' - Satoshi Nakamoto",
// de_DE: "'In der Times vom 03. Januar 2009 stand geschrieben: Der Finanzminister steht kurz vor einer zweiten Bankenrettung' - Satoshi Nakamoto",
// de_CH: "'I dr Times vom 03. Januar 2009 isch gstange: Dr Schatzmeischter isch churz drvor ä zwöiti Bankerettig ufdsgleise' - Satoshi Nakamoto",

String bitcoinSlogans_en[] = {
  "Bitcoin is nerds gold.",
  "In Bitcoin we trust.",
  "Be your own bank.",
  "HODL",
  "Not your keys, not your coins.",
  "There are 100,000,000 sats in a Bitcoin.",
  "Bitcoin was predicted by Henry Ford, Friedrich Hayek and Milton Friedman",
  "Do your own research.",
  "Think for yourself.",
  "Don't delegate your thinking to someone else.",
  "Pursue truth relentlessly.",
  "Love yourself and love others.",
  "Bitcoin is Right.",
  "Be just, be fair and be kind.",
  "If you're afraid of something, study it.",
  "Everybody has a hungry heart.",
  "All humans want the same fundamental things for the same reasons.",
  "No matter how much you have, you will be equally happy.",
  "Having more will not make you happy.",
  "Practice compassion; put yourself in someone else's shoes.",
  "Practice attention; feel without judgement. Experience with curiosity.",
  "Practice gratitude; always find things to be thankful for.",
  "Actions speak louder than words.",
  "What you do determines who you are.",
  "You have a right to property.",
  "Your body is your property.",
  "You are the only one in charge of you.",
  "Your life is yours and yours alone.",
  "Only you can live your life.",
  "Cypherpunks write code.",
  "'If you don't believe me or don't get it, I don't have time to try to convince you, sorry.' - Satoshi Nakamoto",
  "'The heat from your computer is not wasted if you need to heat your home.' - Satoshi Nakamoto",
  "'How does everyone feel about the B symbol with the two lines through the outside?' - Satoshi Nakamoto",
  "'The credential that establishes someone as real is the ability to supply CPU power.' - Satoshi Nakamoto",
  "'For greater privacy, it's best to use bitcoin addresses only once.' - Satoshi Nakamoto",
  "'I'm sure that in 20 years there will either be very large transaction volume or no volume.' - Satoshi Nakamoto",
  "'Lost coins only make everyone else's coins worth slightly more. Think of it as a donation to everyone.' - Satoshi Nakamoto",
  "'Stay humble, stack sats.' - Matt Odell",
  "'Bitcoin is a strange game where the only winning move is to play.' - Bitstein",
  "'If privacy is outlawed, only outlaws will have privacy.' - Phil Zimmermann"
};

String bitcoinSlogans_nl[] = {
  "Bitcoin is goud voor nerds.",
  "We vertrouwen op Bitcoin.",
  "Wees je eigen bank.",
  "HODL",
  "Niet je sleutels, niet je munten.",
  "Er zitten 100 000 000 sats in een Bitcoin.",
  "Bitcoin werd voorspeld door Henry Ford, Friedrich Hayek en Milton Friedman.",
  "Doe je eigen onderzoek.",
  "Denk zelf.",
  "Delegeer je denken niet aan een ander.",
  "Blijf de waarheid opzoeken.",
  "Hou van jezelf en van anderen.",
  "Bitcoin is Juist.",
  "Wees rechtvaardig, eerlijk, en lief.",
  "Als je ergens bang van bent, bestudeer het dan.",
  "Iedereen heeft een hongerig hart.",
  "Alle mensen willen funadmenteel hetzelfde om dezelfde redenen.",
  "Hoe veel je ook hebt, je zal even gelukkig zijn.",
  "Meer hebben zal je niet gelukkiger maken.",
  "Beoefen medeleven; stel jezelf in andermans schoenen.",
  "Beoefen aandacht; voel zonder oordeel. Ervaar met nieuwsgierigheid.",
  "Beoefen dankbaarheid; benoem waar je dankbaar voor bent.",
  "Acties spreken luider dan woorden.",
  "Wat je doet bepaalt wie je bent.",
  "Je hebt recht op eigendom.",
  "Je lichaam is jouw eigendom.",
  "Enkel jij bent baas over jezelf.",
  "Je leven is van alleen van jou.",
  "Enkel jij kan je leven leiden.",
  "Cypherpunks schrijven code.",
  "'Als je me niet gelooft of het niet begrijpt, heb ik geen tijd om je te proberen te overtuigen, sorry.' - Satoshi Nakamoto",
  "'De warmte van je computer wordt niet verspild als je je huis moet verwarmen.' - Satoshi Nakamoto",
  "'Wat vinden jullie van het B symbool met 2 lijnen door de buitenkant?' - Satoshi Nakamoto",
  "'Wat bewijst dat iemand echt is, is dat hij rekenkracht kan leveren.' - Satoshi Nakamoto",
  "'Voor meer privacy is het best om Bitcoin adressen slechts 1 keer te gebruiken.' - Satoshi Nakamoto",
  "'Ik ben zeker dat er binnen 20 jaar ofwel heel veel transacties zullen zijn, ofwel geen enkele.' - Satoshi Nakamoto",
  "'Verloren munten maken gewoon de munten van de anderen iets meer waard. Je kan het beschouwen als een gift aan iedereen.' - Satoshi Nakamoto",
  "'Blijf bescheiden, stapel sats.' - Matt Odell",
  "'Bitcoin is een vreemd spel waarbij het enige wat je kan doen om te winnen, is te spelen.' - Bitstein",
  "'Als privacy illegaal wordt, zullen alleen illegalen privacy hebben.' - Phil Zimmermann"
};

String bitcoinSlogans_da[] = {
  "Bitcoin er nørdernes guld.",
  "Vi tror og stoler på Bitcoin.",
  "Vær din egen bank.",
  "HODL",
  "Ikke dine nøgler, ikke dine bitcoin.",
  "Der er 100.000.000 sats i 1 bitcoin.",
  "Bitcoin blev forudsagt af Henry Ford, Friedrich Hayek og Milton Friedman",
  "Undersøg det selv.",
  "Tænk selv.",
  "Lad ikke andre tænke for dig.",
  "Opsøg altid sandheden, altid.",
  "Elsk dig selv og elsk andre.",
  "Bitcoin har ret.",
  "Vær retfærdig, vær fair og vær venlig.",
  "Hvis du er bange for noget, undersøg det.",
  "Alle har et sultent hjerte.",
  "Alle mennesker ønsker de samme grundlæggende ting af de samme grunde.",
  "Uanset hvor meget du har, vil du være lige så glad.",
  "Having more will not make you happy.",
  "Praktiser medfølelse; sæt dig selv i andres sko.",
  "Praktiser opmærksomhed; føl uden dom. Oplev med nysgerrighed.",
  "Praktiser taknemmelighed; find altid ting at være taknemmelig for.",
  "Handlinger taler højere end ord.",
  "Hvad du gør, bestemmer hvem du er.",
  "Du har ret til ejendom.",
  "Din krop er din ejendom.",
  "Du er den eneste, der bestemmer over dig selv.",
  "Dit liv er dit og kun dit.",
  "Kun du kan leve dit liv.",
  "Cypherpunks skriver kode.",
  "'Hvis du ikke tror på mig eller ikke forstår det, har jeg ikke tid til at prøve at overbevise dig, undskyld.' - Satoshi Nakamoto",
  "'Varmen fra din computer er ikke spildt, hvis du har brug for at opvarme dit hjem.' - Satoshi Nakamoto",
  "'Hvad synes alle om B-symbolet med de to linjer gennem ydersiden?' - Satoshi Nakamoto",
  "'Det legitimationsbevis, der etablerer nogen som ægte, er evnen til at levere CPU-kraft.' - Satoshi Nakamoto",
  "'For bedst mulig privatliv er det foretrukken kun at bruge bitcoin-adresser en gang.' - Satoshi Nakamoto",
  "'Jeg er sikker på, at om 20 år vil der enten være meget stor transaktionsvolumen eller ingen volumen.' - Satoshi Nakamoto",
  "'Mistede mønter gør kun alle andres mønter lidt mere værd. Tænk på det som en donation til alle.' - Satoshi Nakamoto",
  "'Stay humble, stack sats.' - Matt Odell",
  "'Bitcoin er et underligt spil, hvor den eneste vindende bevægelse er at spille.' - Bitstein",
  "'Hvis privatliv er forbudt, vil kun lovbrydere have privatliv.' - Phil Zimmermann"
};

String bitcoinSlogans_de_DE[] = {
  "Bitcoin ist Computerfreak Gold.",
  "In Bitcoin vertrauen wir.",
  "Sei deine eigene Bank.",
  "HODL",
  "Nicht deine Schlüssel, nicht deine Münzen.",
  "Es sind 100,000,000 sats in einem Bitcoin.",
  "Bitcoin wurde von Henry Ford, Friedrich Hayek und Milton Friedman vorhergesagt",
  "Recherchiere selbst.",
  "Denke selbst.",
  "Delegiere das Denken nicht an jemand anderes.",
  "Verfolge die Wahrheit hartnäckig.",
  "Liebe dich selbst und liebe andere.",
  "Bitcoin ist Recht.",
  "Sei gerecht, sei fair und sei freundlich.",
  "Wenn du dich vor etwas fürchtest, erforsche es.",
  "Jeder hat ein hungriges Herz.",
  "Alle Menschen wollen die gleichen grundlegenden Dinge aus den gleichen Gründen.",
  "Egal, wie viel du hast, du wirst gleich glücklich sein.",
  "Mehr zu haben wird dich nicht glücklich machen.",
  "Übe dich in Mitgefühl; versetze dich in die Lage eines anderen.",
  "Übe dich in Aufmerksamkeit; fühle ohne zu urteilen. Erfahre mit Neugierde.",
  "Übe dich in Dankbarkeit; finde immer Dinge, für die du dankbar sein kannst.",
  "Taten sprechen lauter als Worte.",
  "Was du tust, bestimmt, wer du bist.",
  "Du hast ein Recht auf Eigentum.",
  "Dein Körper ist dein Eigentum.",
  "Du bist der Einzige, der für dich zuständig ist.",
  "Dein Leben gehört dir und nur dir allein.",
  "Nur du kannst dein Leben leben.",
  "Cypherpunks schreiben Code.",
  "'Wenn du mir nicht glaubst oder es nicht verstehst, habe ich keine Zeit, dich zu überzeugen, sorry.' - Satoshi Nakamoto",
  "'Die Wärme deines Computers ist nicht verschwendet, wenn du dein Haus damit heizen kannst.' - Satoshi Nakamoto",
  "'Was halten Sie von dem B-Symbol mit den zwei Strichen an der Außenseite?' - Satoshi Nakamoto",
  "'Der Nachweis, der jemanden als echt ausweist, ist die Fähigkeit, CPU-Leistung zu liefern.' - Satoshi Nakamoto",  
  "'Für mehr Privatsphäre ist es am besten, Bitcoin-Adressen nur einmal zu verwenden.' - Satoshi Nakamoto",
  "'Ich bin sicher, dass es in 20 Jahren entweder ein sehr großes Transaktionsvolumen oder gar kein Volumen geben wird.' - Satoshi Nakamoto",
  "'Verlorene Coins machen die Coins aller anderen nur etwas mehr wert. Betrachten Sie es als eine Spende an alle.' - Satoshi Nakamoto",
  "'Bleiben Sie bescheiden, häufen Sie Sats an.' - Matt Odell",
  "'Bitcoin ist ein seltsames Spiel, bei dem der einzige Gewinnzug darin besteht, zu spielen.' - Bitstein",
  "'Wenn die Privatsphäre verboten wird, werden nur noch Gesetzlose eine Privatsphäre haben.' - Phil Zimmermann"
};

String bitcoinSlogans_de_CH[] {
  "Bitcoin isch Goud für Computerfreaks.",
  "Mir vertroue uf Bitcoin.",
  "Muesch dini eigeti Bank si.",
  "HODL",
  "Sis nid dini Wörtli, sis ou nid dini Batzeli.",
  "Es het 100,000,000 sats i eim einzige Bitcoin.",
  "Bitcoin isch vom Henry Ford, Friedrich Hayek u Milton Friedman vorusgseit worde.",
  "Forsch säuber nache.",
  "Dänk säuber.",
  "La nid vo angere für di la dänke.",
  "Muesch d Warheit hartnäckig verfouge.",
  "Lieb di säuber und lieb ou die angere.",
  "Bitcoin isch Rächt.",
  "Bis rächt, fair und fründlech.",
  "Wede vor öppisem Angscht hesch, de tues erforsche.",
  "Jede het es hungrigs Härz.",
  "Aui Mönsche wei die gliche grundlegende Sache us de gliche Gründ.",
  "Egau, wie viu du hesch, du wirsch glich glücklech si.",
  "No meh zha, wird di nid glücklecher mache.",
  "Häb Mitgfüeuh und versetz di id Lag vom de angere.",
  "Üeb di idr Ufmerksamkeit; gspühr ohni z urteile. Erfahr mit Gwunger.",
  "Üeb di idr Dankbarkeit; fing immer Sache, wo du chasch dankbar si drfür.",
  "Richtig handle isch besser aus dumm schnurre.",
  "Was du machsch, bestimmt, wär du bisch.",
  "Du hesch es Rächt uf Eigetum.",
  "Di Körper isch dis Eigetum.",
  "Dr Vättu dobe het di gärn.",
  "Du bisch dr Einzig, wo für di zueständig isch.",
  "Dis Läbe ghört dir u nume dir allei.",
  "Nume du chasch dis Läbe läbe.",
  "Cypherpunks schribe Code.",
  "'We du mir nid gloubsch oder es nid tscheggsch, hani ke Zit dir das no lenger z erkläre, sorry.' - Satoshi Nakamoto",
  "'D Wermi vo dim Computer isch nid vergüdet, wenn du dis Hus drmit heizisch.' - Satoshi Nakamoto",
  "'Wie fingsch das B-Zeiche mit de zwöi Striche am Rand?' - Satoshi Nakamoto",
  "'Dr Nachwis, dass öpper ächt isch, isch sini Fähigkeit Computerleischtig z liefere.' - Satoshi Nakamoto",  
  "'Für meh Privatsphäri isch es am beschte, wede dini Bitcoin-Adrässene nume einisch bruchsch.' - Satoshi Nakamoto",
  "'Ig bi sicher, dass es i 20 Jahr entweder henne viu oder gar keni Transaktione meh git.' - Satoshi Nakamoto",
  "'Verloreni Coins mache d Coins vo aune angere no meh wärt. Luegsch es aus Gschänk für die angere aa.' - Satoshi Nakamoto",
  "'nume nid zgäi, tuesch gschider no chlei sats horte.' - Matt Odell",
  "'Bitcoin isch es komisches Spieli, u dr einzig Siegerzug isch, das Spieli spiele.' - Bitstein",
  "'Wenn d Privatsphäri verbote wird, wärde nume no Gesetzlosi ä Privatsphäri ha.' - Phil Zimmermann"
};

// Function to get a random Bitcoin slogan from the array
String getRandomBootSlogan() {
  if (isConfigured(localeSetting)) {
    if (strncmp(localeSetting,"nl",2) == 0) {
      return getRandomElementFromArray(bitcoinSlogans_nl, sizeof(bitcoinSlogans_nl)/sizeof(bitcoinSlogans_nl[0]));
    } else if (strncmp(localeSetting,"da",2) == 0) {
      return getRandomElementFromArray(bitcoinSlogans_da, sizeof(bitcoinSlogans_da)/sizeof(bitcoinSlogans_da[0]));
    } else if (strncmp(localeSetting,"de_CH",5) == 0) {
      return getRandomElementFromArray(bitcoinSlogans_de_CH, sizeof(bitcoinSlogans_de_CH)/sizeof(bitcoinSlogans_de_CH[0]));
    } else if (strncmp(localeSetting,"de",2) == 0) { // matches de_DE and other de_* locales
      return getRandomElementFromArray(bitcoinSlogans_de_DE, sizeof(bitcoinSlogans_de_DE)/sizeof(bitcoinSlogans_de_DE[0]));
    }
  }

  // Default to Engish
  return getRandomElementFromArray(bitcoinSlogans_en, sizeof(bitcoinSlogans_en)/sizeof(bitcoinSlogans_en[0]));
}
